
nav:
  foldersFirst: false

# render:
#   highlightInclude: true  # light grey, currently left out cause we already have placeholder color (see tesks)

dataPaths:
  Demo 1: 'data/demo_data_1'
  Demo 2: 'data/demo_data_2'
