dataPaths:
  # 'Demo 1':
  #   'data/cmn': '#e8e8e8'
  #   'data/demo_data_1': null
  # 'Demo 2':
  #   'data/cmn': '#e8e8e8'
  #   'data/demo_data_2': null
  AI:
    "G:/Meine Ablage/50 Activity tree/11 Common/Dools/AI (#ai-usage)": null
folderColors:
  - '#fde8e8'
  - '#fef3e2'
  - '#fefde2'
  - '#e8f8e8'
  - '#e2f0fe'
  - '#ede8fe'
  - '#fce8f6'
  - '#e8f4f8'
  - '#f0f0f0'

nav:
  foldersFirst: false
render:
  includedSameIndent: true
  highlightInclude: true
edit:
  autosave: true
