dataPaths:
  # 'Demo 1':
  #   'data/cmn': '#e8e8e8'
  #   'data/demo_data_1': null
  # 'Demo 2':
  #   'data/cmn': '#e8e8e8'
  #   'data/demo_data_2': null
  # 'Prompt demo':
  #   'data/Prompt_demo': null
  Common:
    "G:/Meine Ablage/50 Activity tree/11 Common/Dools/AI (#ai-usage)": null
  Dev:
    "G:/Meine Ablage/50 Activity tree/11 Common/Dools/AI (#ai-usage)": null
    "G:/Meine Ablage/50 Activity tree/11 Common/Dev/prompts": null
  Biz:
    "G:/Meine Ablage/50 Activity tree/11 Common/Dools/AI (#ai-usage)": null
    "G:/Meine Ablage/50 Activity tree/15 VISION  Become superh/11 VISION  Independence (#Indep)/VISION  Fin Unabh (#Biz)/Common/Prompts": null
folderColors:
  red: '#fde8e8'
  orange: '#fef3e2'
  yellow: '#fefde2'
  green: '#e8f8e8'
  blue: '#e2f0fe'
  purple: '#ede8fe'
  pink: '#fce8f6'
  teal: '#e8f4f8'
  gray: '#f0f0f0'

nav:
  foldersFirst: false
render:
  includedSameIndent: true
  highlightInclude: true
edit:
  autosave: true
